### ISSUE TITLE
Error when uploading image: "Can not create a node when the target node is new record."

### ISSUE THREAD

**Issue by Webkadabra** [DevGroup-ru/yii2-media#1]
Request upload url: `http://test.new/media/filesystem/upload`

file: "\vendor\creocoder\yii2-nested-sets\src\NestedSetsBehavior.php"
line: 379
message: "Can not create a node when the target node is new record."
name: "Database Exception"

**Comment by bethrezen** [comment]
Seems some of your models are not passing validation. Without detailed stack trace from logs I can't help you, sorry

**Comment by Webkadabra** [comment]
Looks like you're correct!
